# Generated by Django 5.2.1 on 2025-05-14 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ordenes_trabajo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200, unique=True)),
                (
                    "codigo",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="ordentrabajo",
            name="materiales",
        ),
        migrations.RemoveField(
            model_name="ordentrabajo",
            name="tecnicos",
        ),
        migrations.AddField(
            model_name="ordentrabajo",
            name="tecnicos",
            field=models.TextField(
                blank=True,
                help_text="Ingrese los técnicos separados por comas.",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="MaterialOrden",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.PositiveIntegerField()),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ordenes_trabajo.material",
                    ),
                ),
                (
                    "orden_trabajo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materiales_usados",
                        to="ordenes_trabajo.ordentrabajo",
                    ),
                ),
            ],
            options={
                "unique_together": {("orden_trabajo", "material")},
            },
        ),
    ]
