# Generated by Django 5.2.1 on 2025-05-26 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_trabajo', '0002_material_remove_ordentrabajo_materiales_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='unidad',
            field=models.CharField(default='metros', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='circuito',
            field=models.CharField(default='mtrs', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='horaFin',
            field=models.TimeField(default='12:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='kmFinal',
            field=models.IntegerField(default='35'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='kmInicial',
            field=models.IntegerField(default='35'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='tablero',
            field=models.CharField(default='TC41', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='tecnicos',
            field=models.TextField(blank=True, help_text='Se guarda una lista de técnicos como JSON (nombre y legajo).', null=True),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='vehiculo',
            field=models.CharField(default='kP', max_length=100),
            preserve_default=False,
        ),
    ]
