# Generated by Django 5.2.1 on 2025-06-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_trabajo', '0003_material_unidad_alter_ordentrabajo_circuito_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='unidad',
            field=models.CharField(default='mtrs', max_length=20),
        ),
    ]
